# Generated by Django 5.0.6 on 2025-09-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saaf", "0004_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
