# Generated by Django 5.0.6 on 2025-10-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saaf", "0005_post_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
    ]
