# Generated by Django 5.0.6 on 2025-10-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saaf", "0006_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="post_images/"),
        ),
    ]
